services:
- docker
after_script:
- docker images
before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- IMAGE=plv8:$VERSION
env:
  matrix:
  - VERSION=2.0.3-9.6
  - VERSION=2.0.0-9.6
  global:
  - secure: Q6ScWde8gJxvXVToEheJ24Lp3oS6Hx3856saGJY+rN/bEyZZezGWCbhmMqcjbvqoEMoWbLowmnlAi4eylSoUqEmlkUQV96ZDwpK5QF9gSTkZKNMp9svRejW+lsd/vR/KS4gBdsSeQmsYAzYIwavLgwRrEHkMwwvpBZrlHIW/Oaug491IxDDNkg0ZGbHCIuwrBL5ABCucjVVxngBOeRvxvnrtbdaMyic534/YcAgI81UafV24hg/Gaw2I8iR45V42fl+HKDq9PIJ1TqREmScPcbXbOyr5HqLcC6Fd2tsy5CACKvzxS2cEkYIqidn+PsdsxuakYtosRvOQif0lC/BCgPmJPETkSycGesV1/tzJ7YFmVwZXtcg25Da4W121dVYzzIrZfl1moD5tYpyyHIO8uEHaAPOKTOwGYrLuspHfkbn4WML0ZeSfTEfgX9i7VQ4IS/DwYIsUxciOkun83vb8eI4jd19ZSvtcLYOVJmcfZFhQm9ot0LHzBkxwm8D39W09XOF/jX6klXdx1o0sV8l97sWWBLC+oqZYjUSMqcSKLUHx/K/3K+hG91Z3zjfR/o2eu0R2BpLKPT73oVRJVLXA4nDSwAo+OZ+SIg1RyanflySazmkqq6lRaoS4IhUpfoNJokpzxnXwPys+vWnr+k05xPeMaSH5mi0UiOtEXIgEhsE=
  - secure: oVIqrlnSCim7Ru8SbJMvCX4lUe+WCAVs6SECzTW4pB3TKoGfN2Cl644sCmDIf3sKogOjy4sCTDP8ZYU/JLyjEkXbU20UNr8oR9m/loXZCnbuy2doMngvfabErwzOSavMomEqFToa31zcOXmDI6R4fhlTfujgiw638NBKlb6RNd5/WO5Id1y/PfLppOHSTfkP9gmwLGEApOunoE3/vqDokyxhom8HYl4k82SPeFgxGsFffI3ghE75SBkiCWXq3nvep+NfOQMkkeWuibPlgwcLhiw1wC0j/aKXR+cikHpiH3P+bF/krjkXVsWz6/MDhVyjA9G/wEEe8fUDA7S88joY03Fbg+iyjdIicKeDHbLYYS6qm1nYc60BzfCzLtdMlq4XP54ovNOK6agQRJX3++DA9dN5z2HJJEdWKOZ/YBMXZlixSBqtCtjXMuqoyRuN0YJylJrjzwt2p+vOrCPNIK0UgwBogfMh669XBn1u/I+6xbkCiRL7yD8HWSW5+L4cTWdHmoTmHQL+ZOTm9tp0/qvkwaEA9mVCLSgHFbDjKD29RNRoNy3+ISta9o1bGMlsNkr6fa3t5aSGJ1cthG4PsMv+8rd2VGj+VSHhihp1/wMO2KE3Vr9g79kqSqCj514G9AuXoIgzlncHIcEyBQ2QaGnY/kN/hcSK0HtNMSaZdfp5SK0=
language: bash
script:
- travis_wait 60 docker build -t "${IMAGE}" "${VERSION}"
- docker run -d --name postgres "${IMAGE}"
  && sleep 3
  && while ! docker exec -it postgres pg_isready -U postgres -h 127.0.0.1; do echo "$(date) date for database to start"; sleep 1; done
- docker exec -it postgres psql -U postgres -c 'CREATE EXTENSION plv8; DO $$ plv8.elog(WARNING, plv8.version) $$ LANGUAGE plv8'
- docker exec -it postgres sqitch init project
